### ISSUE TITLE
can't log in and sync google account

### ISSUE THREAD

**Issue by frankkrue** [iridium-browser/tracker#106]
Hello, as i said in the title, i'm unable to log in and sync with my google account.
I can login but nothing happens in iridium 54 x64

**Comment by Chaboris** [comment]
I am having the same problem on x64 and x86 machines using windows 10. The login screen appears and the username and password are accepted. Google even shows a new log in to chrome on the account page but the browser doesn't keep the account.

**Comment by gumbo2** [comment]
Just installed Iridium, same issue I see it has not been attended to since last year November, time to try the next Chromium based browser.

**Comment by GabeEddyT** [comment]
Is this intentional?

**Comment by aktentasche** [comment]
same here, seems like it is intentional...

**Comment by mantisfist** [comment]
I have the same issue, not only with Google account, but with Qwant account. I don't know if this behavior is intentional or not. If it is, they should advise user about it.

**Comment by longsleep** [comment]
Google account sign-in does not work with Iridium. While not directly intentional it kind of defeats the purpose of Iridium if you are signed into Google and report everything to them. From a technical point of view, sign-in to Google requires a Google API key, client ID and client secret and Iridium does not ship with one - thus it does not work.  

If you insist to use Google sign-in, check http://www.chromium.org/developers/how-tos/api-keys and follow the instructions for `Providing Keys at Runtime` and report back here if it works (i have not tested).

**Comment by JeffJMarks** [comment]
I Can't Sign In Into This! Is Kinda Hard!
