### ISSUE TITLE
Access URL Bar in Fullscreen Mode via Ctrl+L

### ISSUE THREAD

**Issue by artofbeinghuman** [iridium-browser/tracker#121]
Hello,

currently when I open a New Tab in Fullscreen Mode, my bookmarks bar is displayed, which is great, but there is no way to access the url bar without exiting the fullscreen mode. 
Often I just want to Ctrl+T out of my PDF and quickly google something, so why not let me access the url bar via Ctrl+L as usual? Maybe make the url bar appear when I access it in fullscreen via Ctrl+L.

Thank you and cheers,
Aobh

**Comment by souldanger** [comment]
Hi Aobh
unfortunately this is a long known problem in Chromium which Iridium is based on.
See how many times this bug has been set back to Wontfix status: [https://bugs.chromium.org/p/chromium/issues/detail?id=8022](https://bugs.chromium.org/p/chromium/issues/detail?id=8022)
This is something, that due to the small development team that we are, we won't be able to fix.
Thank you for your understanding.

**Comment by artofbeinghuman** [comment]
Oh well, such a shame, but totally understandable of course.
Did you mean, that if Google were to implement this feature in the future into the original chromium, it would carry over into iridium eventually?
Thanks a lot for your effort, I'm really enjoying the browser otherwise.

**Comment by souldanger** [comment]
correct!
if it will be fixed in Chromium it will get into the next Iridium release.
Thanks!
