### ISSUE TITLE
Unable to enable/disable extensions on version 58.0!

### ISSUE THREAD

**Issue by tonialb** [iridium-browser/tracker#146]
Hi,

First, thank you for the new version of Iridium.

After updating on v.58.0, noticed that I'm unable to play around with my extensions. I can install them with no problems, but I can't disable or to delete if I want, even after a "reset settings"! Tested both versions of Iridium 32/64bit, portable/standalone, on two different PCs, both with Win7 Ultimate 64bit. Also I tried a clean install, but same result. :(

thanks

**Comment by perfect7gentleman** [comment]
confirm on GNU/Linux Gentoo

**Comment by odebroqueville** [comment]
Same problem on macOS Sierra 10.12.4 running Iridium Version 58.0 (64-bit).

**Comment by souldanger** [comment]
Hi All,
we do apologize for the inconvenience - this is a bug!
It is intentional that you cannot disable built-in extensions, but you should be able to disable added extensions/addons at your discretion.
However, there is a workaround for self-installed extensions;
- go to extension icon right hand side from address bar
- right click icon and then hit 'remove from browser...'
We hope to have this fixed in the next version.

**Comment by minusf** [comment]
still an issue in v61 (2017-10)

**Comment by snowydane** [comment]
Still having this issue.

Version 2017.11 (Official Build) (64-bit)
OS X 10.10.5

**Comment by MST246** [comment]
Also still having this issue. I'm not a Dev but I would not think this should be difficult.

Version 2017.11 (Official Build) (32-bit)
Win 7 SP1

**Comment by souldanger** [comment]
@MST246 Thank you for your input!
I will ignore your comment "I would not think this should be difficult." - it's wee-bit too for from reality to say the least :-)
The problem is as follows:
Extensions in Chromium are managed by Google's Play Store by default. Also the updating process is handled by the Play Store and not the extension itself.
Iridium's key feature is blocking connections to Google (as well as other data crawlers of course) and therefore the Play Store can't handle the extensions. 
In theory, we could setup an updating service for the extensions on our server, but this would make the browser "call home", which then again is against our privacy standards. 
When software "calls home", it is usually rather diffcult to find out what exactly is transmitted or exchanged, which would make Iridium something similar to Chrome and basically pointless...
Thank you for your understanding!

**Comment by mikhoul** [comment]
Same here I can't disable any extensions to test for conflicts, so I will move on another Chromium Fork.

Disabling an extension or removing it  should be easy, now I disable and extension with the toggle button and as soon I reload Chrome://extension it 'show the that the extension is enabled and was never disabled even if the toggle button show them disabled until we refresh the page.

It's a **serious security flaw** since **we can't test for malicious extensions by disabling  or removing them** quickly and easily.

**Comment by azdps** [comment]
Not sure why more emphasis hasn't been devoted to solving this issue. Extensions can be removed from the webui but can't be removed from the extension manager. Since an extension can be removed I don't find removing an extension being an issue.

I do find that **disabling** an extension to be a high priority.  Please devote some time into fixing this bug. I just starting using iridium and this particular bug is quite annoying.

Thank you developers for iridium.

**Comment by Daedalon** [comment]
Currently:

1. Right-clicking an extension's icon at the top right of the browser window: works
2. Clicking Remove on an extension in chrome://extensions/: does nothing
3. Clicking Remove extension in the extension's Details page (chrome://extensions/?id=...): does nothing

It would be good to make 2. and 3. behave the same as 1.

@azdps If you mean that not being able to disable an extension at all is a bigger problem, I agree. However, I believe that broken parts of an UI are also an issue, even if of a lower priority.

**Comment by heronils** [comment]
Hello, thanks for Iridium.

I dont understand why it is necessary to connect to a web service to disable an addon. Is it not enough to just create a text file "disabled.txt" or so in the extension directory, and when Iridium detects that file it ignores the extension? Just asking out of curiosity, i can perfectly live with the decision to only allow installing and uninstalling Extensions.

**Comment by tallos** [comment]
There is zero means to remove an extension that you have disabled. You are unable to re-enable it, and thus there is no icon in the top right for you to uninstall with, as the extensions page is utterly broken.
You are also completely unable to disable or uninstall extensions that have no icon added to the top right, which is a SEVERE security problem should a malicious extension that exploits this gets installed.

**Comment by souldanger** [comment]
@tallos
why would you install a malicious extension? It is obvious that it may cause severe security problems. We've explained in detail why the extension panel does not fully work - it requires a connection to Chrome's webstore that Iridium blocks by default.
Why not use incognito mode, if you would like to do stuff w/o any extensions?

**Comment by tallos** [comment]
@souldanger 
Extensions have been hacked and replaced in the past with malicious ones both in the chrome store, and on separate hosting sites. Noone would knowingly install a malicious extension but often people install ones they think are legit but are malicious. Even if it is a non-malicious extension there is zero way to uninstall ones that do not have an icon in the upper right.
The workaround also leaves no method to re-enable an extension that is accidentally disabled instead of fully uninstalled. If you do manage to disable an extension you are unable to uninstall, reinstall, or enable it, the only fix is reinstalling the entire browser.

**Comment by souldanger** [comment]
@tallos 
Again, we are a small team of developers that do this in their quality time, after work - not an army sized group. Therefore our resources are very, very limited as everybody still has a day job to feed their families.

Please don't get me wrong here, we never had the intention to build a secure and privacy focussed browser that works perfectly with testing extensions - the focus is and always will be on privacy and security. There is simply no point in using a secure browser when you are installing any unsecure extensions that may break all enhancements or contain malware...!
We recommend using a different browser for this. As a wise man once said; _"Iridium Browser works for 95% of your web activities - for everything else use another browser!"_

**Comment by CodeSapiens** [comment]
> Hi All,
> we do apologize for the inconvenience - this is a bug!
> It is intentional that you cannot disable built-in extensions, but you should be able to disable added extensions/addons at your discretion.
> However, there is a workaround for self-installed extensions;
> 
> * go to extension icon right hand side of address bar
> * right click icon and then hit 'remove from browser...'
> 
> We hope to have this fixed in the next version.
> Thanks!

Greetings,
Just letting you know this is still an issue today on the latest Iridium release. I do believe this is a critical issue that needs attention, but looks like the case was marked as Closed for some reason.
I appreciate your time and effort in advance.
Stay safe!

**Comment by Flashwalker** [comment]
And how can i delete extension that has no icon?

**Comment by grand-lotus-iroh** [comment]
still an issue in Version 2020.11 (Official Build) (64-bit) for W10

p.s. - it does let me remove from right click extension in toolbar and remove though :)

**Comment by souldanger** [comment]
@Flashwalker 
try and use the extension manager on the top right 
![extensions-icon](https://user-images.githubusercontent.com/10036776/126333303-1844be50-e719-4faf-aaf6-a9eb3c1966b6.png)

Alternatively, try to delete the extension from ```C:\Users\%user%\AppData\Local\Iridium\User Data\Default\Extensions```  - assuming you are on windows.

**Comment by Flashwalker** [comment]
@souldanger i tried all. I deleted it from C:\Users\%user%\AppData\Local\Iridium\User Data\Default\Extensions, deleted it from Windows registry, but it still persists on browser extensions page, but disabled.

**Comment by Keitaro32** [comment]
Hi

I use Version 2021.12 (Build officiel) (64 bits) but the problem still here :-(
No icon of the extension on the the extension manager on the top right, I can not remove in that way...
I do also the @souldanger solution but as say @Flashwalker it still persists on browser extensions page. :-(

When wil this bug fix ?

**Comment by donaldmcgillavry** [comment]
yes, still the same for me in 2021.12.
disabling, auto-updating as well as **manual** updating of the extensions doesn't work.
BTW, is there a workaround to update an extension manually not from the "Extensions" page?
UPD: found it: https://www.ghacks.net/2018/09/25/how-to-update-chrome-extensions-manually/

**Comment by mavorse** [comment]
Portable Version 2022.04 (Official Build) (32-bit) with -user-data-dir=IridiumUserData
 I can uninstall, but only directly from the menu bar. 
Can't disable plugins. Plugins that manage plugins, also don't work.

**Comment by souldanger** [comment]
please check the [FAQ](https://iridiumbrowser.de/faq) under 'Extensions':
- How to access or remove an extension from the browser?
- Why do certain extensions do not work in Iridium Browser?
