### ISSUE TITLE
Loading traced URL: trk:110:https://android.client.google.com/checkin

### ISSUE THREAD

**Issue by andreas-2017** [iridium-browser/tracker#147]
This error message is displayed directly after starting Iridium browser inside an yellow bubble directly below the address:

`Loading traced URL: trk:110:https://android.client.google.com/checkin`

Iridium Version: 57.0 (64-bit)
Operating system: macOS 10.12.4
Language setting: DE

Additional extensions:

- HTTPS Everywhere 2017.4.5
- if ipv6 1.2
- LastPass 4.1.45
- Save to Pocket 2.1.33
- uBlock Origin 1.12.0
- uBock Origin Extra 2.20

**Comment by souldanger** [comment]
Hi Andreas,
please note our FAQ entry about this:
This helps the development team to find issues with potential privacy problems. The development marks all external URLs they find in the Chromium source code with a ‘trk:’ prefix. Additionally all ‘trk:’ URLs receive a number which makes tracing the code easy i.e. 'git grep trk:173'. When a marked URL is used while browsing, a warning ‘loading traced URL’ in form of a yellow bubble below the address will be displayed, but the request will be executed. This must not appear every time loading a certain URL. If it does, please file a report in our bug tracker on GitHub. In the case trk:173, an update of the spell checker from Google is loaded. From our view no real problem since no client data is submitted.

**Comment by bennetttm** [comment]
how the hell do i get rid of it not to show up at all.  it is irritating and no f*cking use to me.
