### ISSUE TITLE
Loading traced URL after switching Person

### ISSUE THREAD

**Issue by quafzi** [iridium-browser/tracker#149]
I switched to a new profile using the red person icon. After that a yellow message appeared:

`Loading traced URL: trk:271:https://www.gstatic.com/chrome/profile_avatars/avatar_generic_red.png`

**Comment by souldanger** [comment]
#147 
Hi Quafzi,
please note our FAQ entry about this:
This helps the development team to find issues with potential privacy problems. The development marks all external URLs they find in the Chromium source code with a ‘trk:’ prefix. Additionally all ‘trk:’ URLs receive a number which makes tracing the code easy i.e. `git grep trk:173`. When a marked URL is used while browsing, a warning ‘loading traced URL’ in form of a yellow bubble below the address will be displayed, but the request will be executed. This must not appear every time loading a certain URL. If it does, please file a report in our bug tracker on GitHub. In the case trk:173, an update of the spell checker from Google is loaded. From our view no real problem since no client data is submitted.
