### ISSUE TITLE
Is it possible to change file manager dialog from gtk to something else?

### ISSUE THREAD

**Issue by ghost** [iridium-browser/tracker#179]
Right now it uses the default file picker that chromium uses that is the gtk dialog but it has no webm support. I have nautilus installed, can I use it to pick files instead of the gtk one?

**Comment by medozas** [comment]
Unfortunately not possible without a serious redesign of core components which would lead to effectively fork core features/dialogs in chrome. I would recommend to bring this up in the chromium project, since we try to keep chromium the leading project with our "sauce" ontop. Replacing core dialogs is not deemed to be one othe things intended with Iridium.
