### ISSUE TITLE
the problem with passwords

### ISSUE THREAD

**Issue by KAVOR-08** [iridium-browser/tracker#185]
When you try to enter a password hint is highlighted in the "Show saved passwords" . It is alarming and worrying about browser security!! The latest update does not like

**Comment by medozas** [comment]
Unfortunately not possible without a serious redesign of core components which would lead to effectively fork core features/dialogs in chrome. I would recommend to bring this up in the chromium project, since we try to keep chromium the leading project with our "sauce" ontop. Replacing core functionality is not deemed to be one of the things intended with Iridium.
