### ISSUE TITLE
Binary packages out of date despite security issue

### ISSUE THREAD

**Issue by gea0** [iridium-browser/tracker#186]
There were 37 security fixes for chrome on 2017-12-06, one of them critical (CVE-2017-15407).  [0]

But the binary packages available for download are still really outdated,
for example the Ubuntu and Debian versions are from 2017-11-01.

Please fix this as soon as possible. The new versions should be based at least on chrome version 63.0.3239.84

 [0] https://chromereleases.googleblog.com/2017/12/stable-channel-update-for-desktop.html

**Comment by KAVOR-08** [comment]
see you already have The Chromium Project 
65.0.3290.0
--

**Comment by ncoleman** [comment]
We're now in late April 2018 and still no update for Debian since November 2017, despite Chrome having several security fixes over that time.

Fedora has been updated.  Is there some reason Debian hasn't?  Do you need a Debian machine to test on?  Is there some hardship?  Is there a flaw in the build process?  Inquiring minds want to know.

I really like this browser, it does pretty much everything I want.  I can't go back to Firefox derivatives since Mozilla has dropped the ball so badly.  But, I can't be using an insecure browser. Should I consider the project as _Dead_ for Debian?

**Comment by longsleep** [comment]
We build as we have time - sorry for the delay. Debian builds have been updated to 2018.5.
