### ISSUE TITLE
Impossible to install on Debian Strecth

### ISSUE THREAD

**Issue by sylsta** [iridium-browser/tracker#214]
Dear all, 
Thanks for this great project. 
I have a problem when trying to install Iridium

```
sylvain@gozo:~$ sudo apt-get install iridium-browser
[...]
 iridium-browser : Dépend: libfontconfig1 (>= 2.11.94) mais 2.11.0-6.7+b1 devra être installé
```
Sorry it's written in french, but it must be explicit for all. It seems that there is dependecy problem with an up to date debian 9 stretch ( 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux)

Thanks for any advice. 
All the best. 
S.

**Comment by Richard3134** [comment]
Hi Sylsta,

(I am french also)...
[Here](https://github.com/iridium-browser/iridium-browser-ubuntu/issues/15) you will find another thread created for the same question.
The only solution didn't work for me, **and the best thing is to wait a bit** because the member longsleep said:
_I am considering to switch the build system for Iridium for  Debian/Ubuntu to Debian 9 to fix this issue. Will test if feasible and  if so the next build has this resolved._

Have a nice day,
Richard

**Comment by longsleep** [comment]
Since of compiler requirements distros like Debian 9 and Ubuntu 16.04 are becoming too old and thus are harder and harder to support at all. I am closing this for now - let's hope we get Ubuntu 18.04 and Debian 10 working for now.

**Comment by stevenpusser** [comment]
The MX Linux version is built upon and compatible with generic Stretch: 

https://repology.org/project/iridium-browser/versions
