### ISSUE TITLE
Problems with extensions

### ISSUE THREAD

**Issue by metapea** [iridium-browser/tracker#231]
For the windows version:
1. Third parities extensions are being automatically disabled (and even being deleted) with the message of "This extension is not listed in the Chrome Web Store and may have been added without your knowledge" after installing the extensions
2. Extensions seem to be unable to remove itself from the browser (unless you do it manually), once you installed your extensions, you are unable to remove it no matter how many times you click on the "remove" button   

These bugs has been going on for a while in windows 7 and windows 10.

**Comment by souldanger** [comment]
about your issues:
1. please refer to chromium/chrome help. Iridium does not block or disable any extensions. Some extensions may not work due to our privacy & security enhancements.
2. please refer to our [FAQ](https://iridiumbrowser.de/faq) - see "WHY DO EXTENSIONS NOT UPDATE AUTOMATICALLY AND WHY DOES THE EXTENSION PANEL NOT FULLY WORK?"

**Comment by Flashwalker** [comment]
And how can i delete extension that has no icon?
