### ISSUE TITLE
Loading traced URL: trk:113 displays when searching

### ISSUE THREAD

**Issue by richclarke0** [iridium-browser/tracker#348]
There are old versions of this exact ticket that are closed but this is happening to me when doing google searches. The warning appears at the top of the displayed page, underneath the bookmarks bar, the address bar and nav buttons.

![image](https://user-images.githubusercontent.com/77703197/142784992-2d1f0e4b-adbb-412f-9cbe-81a37c66c1e4.png)

It appeared suddenly and without explanation. The browser is upgraded to `iridiumbrowser-2021.10.95.0-x64.msi` and the upgrade did not help.

**Comment by koloved** [comment]
same(

**Comment by Ishiharaerika** [comment]
I feel sorry to remind this problem again because it appears in the latest version again. In just previous version the bar successfully disappeard but it shows again in 2021 Dec. version.
If you developers feel annoying for seeing these kind of feedbacks over and over again, I'm feeling so sorry about that. But it still needs to be mentioned that occassionally Google is still being used in specific searchings. We gratefully understand that it's no longer a good choice. May we have a compromise? Please take some care about this issue. Thank you for reading this complaint...

**Comment by souldanger** [comment]
This is intentional - it tells you, that you are being tracked.
We know it can be annoying, but do feel it is still better to know when you are being tracked.
