### ISSUE TITLE
insecure repositories

### ISSUE THREAD

**Issue by zabbal** [iridium-browser/tracker#80]
While trying to install iridium I"ve got following error after running "apt update"

E: The repository 'https://downloads.iridiumbrowser.de/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

It's pretty alarming to browser with big claims on privacy neglecting basic security practices.

**Comment by Hoshpak** [comment]
I ran in the same issue trying to download the iridium source code with command line tools. Since my browser accepted the certificate but curl and wget didn't. SSLlabs reveals the likely cause:

https://www.ssllabs.com/ssltest/analyze.html?d=downloads.iridiumbrowser.de&s=2a01%3A4f8%3A162%3A73ab%3A0%3A0%3A58c6%3Ab4a4

The web server currently doesn't provide the "Let's Encrypt Authority X3" intermediate certificate which would be needed to verify the certificate chain (graphical browsers usually cache intermediate certificates) but it provides some additional "SwissSign" certificates which I can't see a reason for.

**Comment by medozas** [comment]
Hi there, thanks for reporting. This has been fixed now by putting the webserver to use the correct full chain.

**Comment by zabbal** [comment]
This is unrelated issue - see the error message in the original bug report. The root cause is the absence of Release file which can't be fixed by updating webserver's certificate. Please read the manpage as error message suggests and reopen the bug.

**Comment by Hoshpak** [comment]
Sorry, it was not my intention to hijack this issue. I wrongly assumed that the Release file just couldn't be downloaded because the certificate verification failed. Thanks to @medozas for fixing the certificate issue though.

**Comment by medozas** [comment]
@zabbal : Thanks, the issue was indeed hijacked by @Hoshpak ;) - No worries, we are about to release new packages for Debian/Ubuntu, the issue will be fixed then in one go. I'm reopening this ticket for the moment and ask for confirmation as soon as the new packages are online (ETA due to holiday season around 2 weeks)

**Comment by souldanger** [comment]
Hi guys
new Debian / Ubuntu packages are now online. see [https://iridiumbrowser.de/download.html](https://iridiumbrowser.de/download.html)
Please do let us know if you run into any problems.
Thanks!

**Comment by iteco** [comment]
I installed iridium browser when I had ubuntu 14.04 in use, based on your download page instructions (https://iridiumbrowser.de/download.html). Since then I have upgraded to ubuntu 16.04 (like most probably).

now 
sudo apt-get update gave following order.

W: Conflicting distribution: https://downloads.iridiumbrowser.de trusty InRelease (expected trusty but got stable)
W: Failed to fetch https://downloads.iridiumbrowser.de/ubuntu/dists/trusty/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

Can you fix that ?

**Comment by longsleep** [comment]
This is all fixed, update the repository according to the updated docs 

```
wget -qO - https://downloads.iridiumbrowser.de/ubuntu/iridium-release-sign-01.pub|sudo apt-key add -
cat <<EOF | sudo tee /etc/apt/sources.list.d/iridium-browser.list
deb [arch=amd64] https://downloads.iridiumbrowser.de/deb/ stable main
#deb-src https://downloads.iridiumbrowser.de/deb/ stable main
EOF
sudo apt-get update
sudo apt-get install iridium-browser
```

Also the repository has been using a secure URL since ever. The initial issue was about then there was no build for Ubuntu Xenial which is totally different from having a non-secure repository.
